-- AlterTable
ALTER TABLE "fuel_interaction" ALTER COLUMN "capacity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "before_refueling" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "after_refueling" SET DATA TYPE DOUBLE PRECISION;
